# most personal metadata can be found in ./resume.json

- description: Portfolio of web &amp; ui designer/developer hybrid Herman Ozols.
  img: ../src/images/twitter-card.png

  availability: 
    status: true
    available: '👔 Available for new projects. <a href="mailto:h11ozols@gmail.com">Let’s talk</a>!'
    unavailable: Not available for new projects.

  # Footer actions
  gpg: https://kretschmann.io/pub.gpg
  addressbook: /matthias-kretschmann.vcf
  bugs: https://github.com/kremalicious/portfolio/issues/new

  # Analytics tools
  matomoUrl: https://analytics.kremalicious.com
  matomoSite: 2

  allowedHosts:
    - matthiaskretschmann.com
    - beta.matthiaskretschmann.com
    - localhost
    - 05.local
